import { computeTrustScore } from "./verification.utils";
import type { TrustScoreBreakdown, VerificationRow } from "./types";

/**
 * Mock verification case rows for /admin/verifications — covers all four
 * verification types (email, phone, profile, manual review) across a range
 * of statuses, priorities, and roles.
 * TODO: Replace with: await db.verification.findMany({ ...pagination, ...filters })
 *   joined with the user's TrustScore record.
 */

function breakdown(b: TrustScoreBreakdown) {
  return { breakdown: b, score: computeTrustScore(b) };
}

const roshan = breakdown({
  profileCompleteness: 92,
  contactVerification: 100,
  accountHistory: 85,
  reviewsRatings: 90,
  communitySafety: 80,
});

const sunita = breakdown({
  profileCompleteness: 70,
  contactVerification: 70,
  accountHistory: 55,
  reviewsRatings: 60,
  communitySafety: 40,
});

const maya = breakdown({
  profileCompleteness: 100,
  contactVerification: 100,
  accountHistory: 95,
  reviewsRatings: 98,
  communitySafety: 100,
});

const bikash = breakdown({
  profileCompleteness: 40,
  contactVerification: 50,
  accountHistory: 20,
  reviewsRatings: 10,
  communitySafety: 15,
});

const anita = breakdown({
  profileCompleteness: 85,
  contactVerification: 100,
  accountHistory: 70,
  reviewsRatings: 75,
  communitySafety: 60,
});

const rajesh = breakdown({
  profileCompleteness: 55,
  contactVerification: 50,
  accountHistory: 40,
  reviewsRatings: 30,
  communitySafety: 35,
});

const priya = breakdown({
  profileCompleteness: 60,
  contactVerification: 100,
  accountHistory: 50,
  reviewsRatings: 45,
  communitySafety: 50,
});

const sabina = breakdown({
  profileCompleteness: 30,
  contactVerification: 0,
  accountHistory: 10,
  reviewsRatings: 0,
  communitySafety: 20,
});

export const MOCK_VERIFICATIONS: VerificationRow[] = [
  {
    id: "VER-1001",
    userId: "u1",
    userDisplayId: "USR-89322",
    userName: "Roshan Adhikari",
    userEmail: "roshan.adhikari@email.com",
    userPhone: "+977 9801122334",
    role: "user",
    memberSince: "2024-02-12",
    primaryType: "profile",
    status: "pending",
    priority: "normal",
    trustScore: roshan.score,
    trustScoreSummary: "Strong profile and contact verification with positive account history.",
    signals: [
      { key: "email", label: "Email Verified", active: true },
      { key: "phone", label: "Phone Verified", active: true },
      { key: "profile", label: "Profile Complete", active: true },
      { key: "reviews", label: "Positive Reviews", active: true },
    ],
    channels: { email: "verified", phone: "verified", profile: "complete", manualReview: "not_started" },
    trustBreakdown: roshan.breakdown,
    safety: {
      accountAge: "2 years, 4 months",
      successfulBookings: 2,
      activeListings: 0,
      completedConnections: 3,
      reviewsReceived: 8,
      activeReports: 0,
      resolvedReports: 0,
      previousWarnings: 0,
    },
    history: [
      { label: "Profile completed", timestamp: "2026-02-12T09:00:00", actor: "System" },
      { label: "Email verified", timestamp: "2026-02-12T09:05:00", actor: "System" },
      { label: "Phone verified", timestamp: "2026-02-13T14:20:00", actor: "System" },
      { label: "Submitted for profile verification", timestamp: "2026-07-20T10:00:00", actor: "System" },
    ],
    notes: [],
    submittedAt: "2026-07-20T10:00:00",
  },
  {
    id: "VER-1002",
    userId: "u2",
    userDisplayId: "USR-77410",
    userName: "Sunita Gurung",
    userEmail: "sunita.gurung@email.com",
    userPhone: "+977 9812233445",
    role: "tenant",
    memberSince: "2023-11-05",
    primaryType: "manual_review",
    status: "needs_attention",
    priority: "high",
    trustScore: sunita.score,
    trustScoreSummary: "Contact verified, but recent reports require a manual safety review.",
    signals: [
      { key: "email", label: "Email Verified", active: true },
      { key: "phone", label: "Phone Verified", active: true },
      { key: "profile", label: "Profile Complete", active: true },
      { key: "no_reports", label: "No Active Reports", active: false },
    ],
    channels: { email: "verified", phone: "verified", profile: "complete", manualReview: "under_review" },
    trustBreakdown: sunita.breakdown,
    safety: {
      accountAge: "1 year, 9 months",
      successfulBookings: 5,
      activeListings: 2,
      completedConnections: 1,
      reviewsReceived: 4,
      activeReports: 2,
      resolvedReports: 1,
      previousWarnings: 1,
      suspiciousActivityNote: "Two tenants reported inconsistent listing photos within the last 30 days.",
    },
    history: [
      { label: "Profile completed", timestamp: "2023-11-06T09:00:00", actor: "System" },
      { label: "Email verified", timestamp: "2023-11-06T09:10:00", actor: "System" },
      { label: "Phone verified", timestamp: "2023-11-07T11:00:00", actor: "System" },
      { label: "Report received", timestamp: "2026-07-18T08:30:00", actor: "System" },
      { label: "Submitted for manual review", timestamp: "2026-07-19T09:00:00", actor: "System" },
      { label: "Review started", timestamp: "2026-07-19T13:00:00", actor: "Admin: Kritika S." },
    ],
    notes: [
      {
        id: "n1",
        authorName: "Kritika S.",
        message: "Reviewing listing photo mismatches reported by two tenants. Awaiting owner response.",
        createdAt: "2026-07-19T13:05:00",
      },
    ],
    submittedAt: "2026-07-19T09:00:00",
  },
  {
    id: "VER-1003",
    userId: "u3",
    userDisplayId: "USR-90112",
    userName: "Maya Karki",
    userEmail: "maya.karki@email.com",
    userPhone: "+977 9845566778",
    role: "user",
    memberSince: "2022-06-18",
    primaryType: "profile",
    status: "verified",
    priority: "low",
    trustScore: maya.score,
    trustScoreSummary: "Excellent history across every trust signal — a long-standing, highly engaged member.",
    signals: [
      { key: "email", label: "Email Verified", active: true },
      { key: "phone", label: "Phone Verified", active: true },
      { key: "profile", label: "Profile Complete", active: true },
      { key: "history", label: "Account History", active: true },
      { key: "reviews", label: "Positive Reviews", active: true },
      { key: "bookings", label: "Successful Bookings", active: true },
      { key: "no_reports", label: "No Active Reports", active: true },
      { key: "community", label: "Community Activity", active: true },
    ],
    channels: { email: "verified", phone: "verified", profile: "complete", manualReview: "verified" },
    trustBreakdown: maya.breakdown,
    safety: {
      accountAge: "4 years, 1 month",
      successfulBookings: 9,
      activeListings: 0,
      completedConnections: 6,
      reviewsReceived: 22,
      activeReports: 0,
      resolvedReports: 0,
      previousWarnings: 0,
    },
    history: [
      { label: "Profile completed", timestamp: "2022-06-19T09:00:00", actor: "System" },
      { label: "Email verified", timestamp: "2022-06-19T09:05:00", actor: "System" },
      { label: "Phone verified", timestamp: "2022-06-20T10:00:00", actor: "System" },
      { label: "Marked as verified", timestamp: "2022-07-01T12:00:00", actor: "Admin: Prakash T." },
    ],
    notes: [],
    submittedAt: "2022-06-19T09:00:00",
  },
  {
    id: "VER-1004",
    userId: "u4",
    userDisplayId: "USR-65210",
    userName: "Bikash Shrestha",
    userEmail: "bikash.shrestha@email.com",
    userPhone: "+977 9823344556",
    role: "user",
    memberSince: "2026-06-30",
    primaryType: "manual_review",
    status: "suspended",
    priority: "urgent",
    trustScore: bikash.score,
    trustScoreSummary: "Multiple unresolved reports and a very low account-history signal triggered a suspension.",
    signals: [
      { key: "email", label: "Email Verified", active: true },
      { key: "phone", label: "Phone Verified", active: false },
      { key: "profile", label: "Profile Complete", active: false },
      { key: "no_reports", label: "No Active Reports", active: false },
    ],
    channels: { email: "verified", phone: "failed", profile: "incomplete", manualReview: "suspended" },
    trustBreakdown: bikash.breakdown,
    safety: {
      accountAge: "3 weeks",
      successfulBookings: 0,
      activeListings: 1,
      completedConnections: 0,
      reviewsReceived: 0,
      activeReports: 3,
      resolvedReports: 0,
      previousWarnings: 2,
      suspiciousActivityNote: "Multiple users reported the same listing posted under different names.",
    },
    history: [
      { label: "Profile completed", timestamp: "2026-06-30T09:00:00", actor: "System" },
      { label: "Email verified", timestamp: "2026-06-30T09:10:00", actor: "System" },
      { label: "Phone verification failed", timestamp: "2026-07-01T10:00:00", actor: "System" },
      { label: "Report received", timestamp: "2026-07-10T08:00:00", actor: "System" },
      { label: "Report received", timestamp: "2026-07-12T09:00:00", actor: "System" },
      { label: "Account suspended", timestamp: "2026-07-14T11:00:00", actor: "Admin: Kritika S." },
    ],
    notes: [
      {
        id: "n2",
        authorName: "Kritika S.",
        message: "Suspended pending investigation into duplicate listing reports. Do not reinstate without review.",
        createdAt: "2026-07-14T11:05:00",
      },
    ],
    submittedAt: "2026-07-10T08:00:00",
  },
  {
    id: "VER-1005",
    userId: "u5",
    userDisplayId: "USR-71029",
    userName: "Anita Gurung",
    userEmail: "anita.gurung@email.com",
    userPhone: "+977 9856677889",
    role: "tenant",
    memberSince: "2025-01-22",
    primaryType: "phone",
    status: "under_review",
    priority: "normal",
    trustScore: anita.score,
    trustScoreSummary: "Solid profile and contact signals; phone verification is being re-confirmed after a number change.",
    signals: [
      { key: "email", label: "Email Verified", active: true },
      { key: "phone", label: "Phone Verified", active: true },
      { key: "profile", label: "Profile Complete", active: true },
      { key: "reviews", label: "Positive Reviews", active: true },
    ],
    channels: { email: "verified", phone: "pending", profile: "complete", manualReview: "not_started" },
    trustBreakdown: anita.breakdown,
    safety: {
      accountAge: "1 year, 6 months",
      successfulBookings: 4,
      activeListings: 3,
      completedConnections: 2,
      reviewsReceived: 11,
      activeReports: 0,
      resolvedReports: 1,
      previousWarnings: 0,
    },
    history: [
      { label: "Profile completed", timestamp: "2025-01-23T09:00:00", actor: "System" },
      { label: "Email verified", timestamp: "2025-01-23T09:10:00", actor: "System" },
      { label: "Phone number updated", timestamp: "2026-07-15T14:00:00", actor: "System" },
      { label: "Phone re-verification requested", timestamp: "2026-07-15T14:05:00", actor: "System" },
    ],
    notes: [],
    submittedAt: "2026-07-15T14:05:00",
  },
  {
    id: "VER-1006",
    userId: "u6",
    userDisplayId: "USR-58821",
    userName: "Rajesh Hamal",
    userEmail: "rajesh.hamal@email.com",
    userPhone: "+977 9834455667",
    role: "tenant",
    memberSince: "2026-05-10",
    primaryType: "manual_review",
    status: "rejected",
    priority: "high",
    trustScore: rajesh.score,
    trustScoreSummary: "Conflicting property ownership information could not be reconciled during review.",
    signals: [
      { key: "email", label: "Email Verified", active: true },
      { key: "phone", label: "Phone Verified", active: false },
      { key: "profile", label: "Profile Complete", active: true },
      { key: "no_reports", label: "No Active Reports", active: true },
    ],
    channels: { email: "verified", phone: "pending", profile: "complete", manualReview: "rejected" },
    trustBreakdown: rajesh.breakdown,
    safety: {
      accountAge: "2 months",
      successfulBookings: 0,
      activeListings: 0,
      completedConnections: 0,
      reviewsReceived: 0,
      activeReports: 0,
      resolvedReports: 0,
      previousWarnings: 0,
    },
    history: [
      { label: "Profile completed", timestamp: "2026-05-11T09:00:00", actor: "System" },
      { label: "Email verified", timestamp: "2026-05-11T09:10:00", actor: "System" },
      { label: "Submitted for manual review", timestamp: "2026-06-01T10:00:00", actor: "System" },
      { label: "Additional verification requested", timestamp: "2026-06-05T09:00:00", actor: "Admin: Prakash T." },
      { label: "Verification rejected", timestamp: "2026-06-10T15:00:00", actor: "Admin: Prakash T." },
    ],
    notes: [
      {
        id: "n3",
        authorName: "Prakash T.",
        message: "Property ownership details provided did not match the listing address on file. Rejected pending resubmission.",
        createdAt: "2026-06-10T15:05:00",
      },
    ],
    submittedAt: "2026-06-01T10:00:00",
  },
  {
    id: "VER-1007",
    userId: "u7",
    userDisplayId: "USR-40217",
    userName: "Priya Sharma",
    userEmail: "priya.sharma@email.com",
    userPhone: "+977 9867788990",
    role: "user",
    memberSince: "2025-09-02",
    primaryType: "profile",
    status: "pending",
    priority: "low",
    trustScore: priya.score,
    trustScoreSummary: "Contact fully verified; profile is still missing living-preference details.",
    signals: [
      { key: "email", label: "Email Verified", active: true },
      { key: "phone", label: "Phone Verified", active: true },
      { key: "profile", label: "Profile Complete", active: false },
    ],
    channels: { email: "verified", phone: "verified", profile: "incomplete", manualReview: "not_started" },
    trustBreakdown: priya.breakdown,
    safety: {
      accountAge: "10 months",
      successfulBookings: 1,
      activeListings: 0,
      completedConnections: 1,
      reviewsReceived: 2,
      activeReports: 0,
      resolvedReports: 0,
      previousWarnings: 0,
    },
    history: [
      { label: "Email verified", timestamp: "2025-09-02T09:10:00", actor: "System" },
      { label: "Phone verified", timestamp: "2025-09-03T10:00:00", actor: "System" },
      { label: "Submitted for profile verification", timestamp: "2026-07-21T08:00:00", actor: "System" },
    ],
    notes: [],
    submittedAt: "2026-07-21T08:00:00",
  },
  {
    id: "VER-1008",
    userId: "u8",
    userDisplayId: "USR-33109",
    userName: "Sabina Rai",
    userEmail: "sabina.rai@email.com",
    userPhone: "+977 9878899001",
    role: "user",
    memberSince: "2026-07-19",
    primaryType: "email",
    status: "pending",
    priority: "normal",
    trustScore: sabina.score,
    trustScoreSummary: "New account — awaiting first contact verification steps.",
    signals: [
      { key: "email", label: "Email Verified", active: false },
      { key: "phone", label: "Phone Verified", active: false },
      { key: "profile", label: "Profile Complete", active: false },
    ],
    channels: { email: "pending", phone: "pending", profile: "incomplete", manualReview: "not_started" },
    trustBreakdown: sabina.breakdown,
    safety: {
      accountAge: "4 days",
      successfulBookings: 0,
      activeListings: 0,
      completedConnections: 0,
      reviewsReceived: 0,
      activeReports: 0,
      resolvedReports: 0,
      previousWarnings: 0,
    },
    history: [{ label: "Account created", timestamp: "2026-07-19T16:00:00", actor: "System" }],
    notes: [],
    submittedAt: "2026-07-19T16:00:00",
  },
];
