import type { AdminReportRow } from "./types";

/**
 * Mock report queue rows for /admin/reports.
 * TODO: Replace with: await db.report.findMany({ ...pagination, ...filters })
 */
export const MOCK_REPORTS: AdminReportRow[] = [
  {
    id: "r1",
    displayId: "REP-8821",
    reporterName: "Anil Karki",
    reportedUserName: "Bishal Thapa",
    reason: "abuse",
    evidenceFile: "Screen_01.jpg",
    evidenceType: "image",
    priority: "high",
    lastActivity: "New",
    queueStatus: "pending",
    createdAt: "2024-01-15T09:12:00Z",
  },
  {
    id: "r2",
    displayId: "REP-8819",
    reporterName: "Sunita Rai",
    reportedUserName: "Rajesh Hamal",
    reason: "spam",
    evidenceFile: "chat_log.ext",
    evidenceType: "chat",
    priority: "medium",
    lastActivity: "Active 2m ago",
    queueStatus: "in_review",
    createdAt: "2024-01-15T08:40:00Z",
  },
  {
    id: "r3",
    displayId: "REP-8815",
    reporterName: "Deepa Pandey",
    reportedUserName: "Suman Gurung",
    reason: "false_info",
    priority: "low",
    lastActivity: "New",
    queueStatus: "pending",
    createdAt: "2024-01-14T18:05:00Z",
  },
  {
    id: "r4",
    displayId: "REP-8798",
    reporterName: "Bikash Shrestha",
    reportedUserName: "Anita Gurung",
    reason: "fake_listing",
    evidenceFile: "listing_photos.zip",
    evidenceType: "document",
    priority: "high",
    lastActivity: "Under review",
    queueStatus: "in_review",
    createdAt: "2024-01-13T14:22:00Z",
  },
  {
    id: "r5",
    displayId: "REP-8770",
    reporterName: "Priya Sharma",
    reportedUserName: "Ramesh Thapa",
    reason: "scam",
    evidenceFile: "payment_proof.pdf",
    evidenceType: "document",
    priority: "high",
    lastActivity: "Resolved 1d ago",
    queueStatus: "resolved",
    createdAt: "2024-01-10T11:00:00Z",
  },
  {
    id: "r6",
    displayId: "REP-8752",
    reporterName: "Sabina Rai",
    reportedUserName: "Nikita Rai",
    reason: "other",
    priority: "low",
    lastActivity: "Dismissed",
    queueStatus: "dismissed",
    createdAt: "2024-01-08T10:00:00Z",
  },
];
