/**
 * Shared mock data used by:
 *  - app/(public)/listings/page.tsx
 *  - app/(public)/roommates/page.tsx
 *  - app/(public)/page.tsx  (landing page featured sections)
 *
 * Replace with real DB queries when the backend is ready.
 */

import type { RoommateData } from "@/components/roommates/roommate-card";
import type { RoomListingData } from "@/components/roo/room-card/page";

// ─── Portrait photos (people) ────────────────────────────────────────────────
export const PERSON_PHOTOS = {
  manSuit:       "/photo-1519085360753-af0119f7cbe7.avif",
  womanProf:     "/photo-1573496359142-b8d87734a5a2.avif",
  person1:       "/photo-1612320648993-61c1cd604b71.avif",
  womanPortrait: "/premium_photo-1664471481572-c59a951a7755.avif",
  person2:       "/premium_photo-1677368597077-009727e906db.avif",
  person3:       "/premium_photo-1683887034491-f58b4c4fca72.avif",
  person4:       "/premium_photo-1689609950112-d66095626efb.avif",
  person5:       "/premium_photo-1658506656752-4f1b1c1d5916.avif",
  istockPerson:  "/istockphoto-1149822847-612x612.webp",
};

// ─── Room / interior photos ───────────────────────────────────────────────────
export const ROOM_PHOTOS = {
  roomBright:   "/photo-1512918728675-ed5a9ecdebfd.avif",
  roomModern:   "/photo-1544717305-2782549b5136.avif",
  roomCozy:     "/photo-1589386417686-0d34b5903d23.avif",
  roomLarge:    "/photo-1616594039964-ae9021a400a0.avif",
  building1:    "/pexels-szafran-37485325.jpg",
  building2:    "/pexels-alinaskazka-20094613.jpg",
  building3:    "/pexels-akram-bouchar-106103116-10357202.jpg",
};

// ─── Roommate mock data ───────────────────────────────────────────────────────
export const MOCK_ROOMMATES: RoommateData[] = [
  {
    id: "1",
    name: "Sagar Kumar",
    age: 24,
    occupation: "Medical Student at TUTH",
    location: "Thamel, Kathmandu",
    budget: 8000,
    moveInDate: "April 2025",
    photo: PERSON_PHOTOS.manSuit,
    bio: "I'm a medical student looking for a clean, quiet roommate. I usually study late nights and wake up early. Non-smoker, vegetarian, and I love keeping shared spaces organized.",
    compatibilityScore: 94,
    trustScore: 88,
    isVerified: true,
    rating: 4.8,
    reviewCount: 12,
    responseTime: "< 1 hour",
    lifestyleChips: ["Non-Smoker", "Vegetarian", "Gym Freak", "Early Bird"],
    compatibilityReasons: ["Same Budget Range", "Similar Work Schedule", "Both Non-Smokers", "Same Preferred Area"],
  },
  {
    id: "2",
    name: "Nikita Rai",
    age: 22,
    occupation: "Graphic Designer at Tech Co",
    location: "Lazimpat, Kathmandu",
    budget: 12000,
    moveInDate: "May 2025",
    photo: PERSON_PHOTOS.womanProf,
    bio: "Creative professional working remotely. I appreciate a clean space and love cooking. Looking for someone chill and respectful of work hours.",
    compatibilityScore: 87,
    trustScore: 92,
    isVerified: true,
    rating: 4.9,
    reviewCount: 18,
    responseTime: "< 2 hours",
    lifestyleChips: ["Art Lover", "Quiet", "Remote Worker", "Clean"],
    compatibilityReasons: ["Similar Lifestyle", "Compatible Work Hours", "Both Value Cleanliness"],
  },
  {
    id: "3",
    name: "Arun Magar",
    age: 26,
    occupation: "Software Engineer",
    location: "Patan, Lalitpur",
    budget: 15000,
    moveInDate: "March 2025",
    photo: PERSON_PHOTOS.person1,
    compatibilityScore: 76,
    trustScore: 85,
    isVerified: true,
    rating: 4.7,
    reviewCount: 9,
    responseTime: "< 3 hours",
    lifestyleChips: ["Early Bird", "Clean", "Tech Enthusiast", "Gym"],
  },
  {
    id: "4",
    name: "Priya Sharma",
    age: 23,
    occupation: "MBA Student",
    location: "Chabahil, Kathmandu",
    budget: 10000,
    moveInDate: "April 2025",
    photo: PERSON_PHOTOS.womanPortrait,
    compatibilityScore: undefined,
    trustScore: 78,
    isVerified: false,
    rating: 4.5,
    reviewCount: 6,
    responseTime: "< 4 hours",
    lifestyleChips: ["Vegetarian", "Neat", "Night Owl", "Foodie"],
  },
  {
    id: "5",
    name: "Ramesh Thapa",
    age: 27,
    occupation: "Marketing Manager",
    location: "Baluwatar, Kathmandu",
    budget: 18000,
    moveInDate: "June 2025",
    photo: PERSON_PHOTOS.person2,
    compatibilityScore: 91,
    trustScore: 95,
    isVerified: true,
    rating: 5.0,
    reviewCount: 24,
    responseTime: "< 30 min",
    lifestyleChips: ["Clean", "Professional", "Non-Smoker", "Pet Friendly"],
    compatibilityReasons: ["Excellent Budget Match", "Similar Professional Background", "Both Pet Friendly"],
  },
  {
    id: "6",
    name: "Anita Rai",
    age: 25,
    occupation: "Content Writer",
    location: "Lakeside, Pokhara",
    budget: 9000,
    moveInDate: "April 2025",
    photo: PERSON_PHOTOS.person3,
    compatibilityScore: 83,
    trustScore: 81,
    isVerified: true,
    rating: 4.6,
    reviewCount: 11,
    responseTime: "< 2 hours",
    lifestyleChips: ["Quiet", "Remote Worker", "Bookworm", "Vegetarian"],
  },
  {
    id: "7",
    name: "Suresh Basnet",
    age: 28,
    occupation: "Civil Engineer",
    location: "Bhaktapur",
    budget: 11000,
    moveInDate: "May 2025",
    photo: PERSON_PHOTOS.person4,
    compatibilityScore: 79,
    trustScore: 87,
    isVerified: true,
    rating: 4.4,
    reviewCount: 8,
    responseTime: "< 3 hours",
    lifestyleChips: ["Non-Smoker", "Gym", "Early Bird", "Clean"],
  },
  {
    id: "8",
    name: "Meera Poudel",
    age: 24,
    occupation: "Nurse at Teaching Hospital",
    location: "Maharajgunj, Kathmandu",
    budget: 7500,
    moveInDate: "June 2025",
    photo: PERSON_PHOTOS.person5,
    compatibilityScore: 88,
    trustScore: 90,
    isVerified: true,
    rating: 4.8,
    reviewCount: 15,
    responseTime: "< 1 hour",
    lifestyleChips: ["Quiet", "Non-Smoker", "Vegetarian", "Early Bird"],
    compatibilityReasons: ["Same Lifestyle Values", "Compatible Schedules", "Both Non-Smokers"],
  },
];

// ─── Room listing mock data ───────────────────────────────────────────────────
export const MOCK_LISTINGS: RoomListingData[] = [
  {
    id: "listing-1",
    title: "Cozy Room in Thamel",
    type: "room",
    location: "Thamel, Kathmandu",
    price: 8000,
    photo: ROOM_PHOTOS.roomBright,
    isVerified: true,
    genderPreference: "any",
    amenities: ["WiFi", "Furnished"],
    rating: 4.6,
    reviewCount: 14,
    availableFrom: "Now",
    landlordTrustScore: 88,
    postedDaysAgo: 2,
  },
  {
    id: "listing-2",
    title: "Modern Studio Flat",
    type: "apartment",
    location: "Lazimpat, Kathmandu",
    price: 12000,
    photo: ROOM_PHOTOS.roomModern,
    isVerified: true,
    genderPreference: "female",
    amenities: ["Parking", "Kitchen", "WiFi"],
    rating: 4.8,
    reviewCount: 22,
    availableFrom: "1 May",
    landlordTrustScore: 92,
    postedDaysAgo: 1,
    matchScore: 91,
    matchReasons: ["Budget Match", "Preferred Area"],
  },
  {
    id: "listing-3",
    title: "Shared Apartment",
    type: "apartment",
    location: "Patan, Lalitpur",
    price: 15000,
    photo: ROOM_PHOTOS.roomCozy,
    isVerified: false,
    genderPreference: "male",
    amenities: ["Security", "Water"],
    rating: 4.3,
    reviewCount: 7,
    availableFrom: "15 May",
    postedDaysAgo: 5,
  },
  {
    id: "listing-4",
    title: "Spacious PG Room",
    type: "pg",
    location: "Lakeside, Pokhara",
    price: 6500,
    photo: ROOM_PHOTOS.roomLarge,
    isVerified: true,
    genderPreference: "female",
    amenities: ["WiFi", "Meals Included"],
    rating: 4.5,
    reviewCount: 18,
    availableFrom: "Now",
    landlordTrustScore: 84,
    postedDaysAgo: 3,
    matchScore: 85,
    matchReasons: ["Budget Match", "Great Location"],
  },
  {
    id: "listing-5",
    title: "Furnished Hostel Room",
    type: "hostel",
    location: "Chabahil, Kathmandu",
    price: 4500,
    photo: ROOM_PHOTOS.building1,
    isVerified: true,
    genderPreference: "male",
    amenities: ["Laundry", "WiFi"],
    rating: 4.1,
    reviewCount: 9,
    availableFrom: "Now",
    postedDaysAgo: 7,
  },
  {
    id: "listing-6",
    title: "Luxury Apartment Share",
    type: "apartment",
    location: "Lazimpat, Kathmandu",
    price: 25000,
    photo: ROOM_PHOTOS.building2,
    isVerified: true,
    genderPreference: "any",
    amenities: ["Gym", "Parking", "WiFi", "Security"],
    rating: 4.9,
    reviewCount: 31,
    availableFrom: "1 Jun",
    landlordTrustScore: 96,
    postedDaysAgo: 1,
    matchScore: 78,
  },
  {
    id: "listing-7",
    title: "Budget Room Near Tribhuvan University",
    type: "room",
    location: "Kirtipur, Kathmandu",
    price: 5500,
    photo: ROOM_PHOTOS.roomBright,
    isVerified: false,
    genderPreference: "male",
    amenities: ["WiFi"],
    rating: 4.0,
    reviewCount: 4,
    availableFrom: "Now",
    postedDaysAgo: 10,
  },
  {
    id: "listing-8",
    title: "Modern PG with Rooftop",
    type: "pg",
    location: "Baluwatar, Kathmandu",
    price: 11000,
    photo: ROOM_PHOTOS.roomModern,
    isVerified: true,
    genderPreference: "female",
    amenities: ["Meals Included", "WiFi", "Laundry"],
    rating: 4.7,
    reviewCount: 16,
    availableFrom: "15 Apr",
    landlordTrustScore: 89,
    postedDaysAgo: 4,
  },
  {
    id: "listing-9",
    title: "Peaceful Flat in Bhaktapur",
    type: "apartment",
    location: "Bhaktapur",
    price: 9000,
    photo: ROOM_PHOTOS.roomCozy,
    isVerified: true,
    genderPreference: "any",
    amenities: ["Parking", "Water"],
    rating: 4.4,
    reviewCount: 11,
    availableFrom: "Now",
    postedDaysAgo: 6,
  },
  {
    id: "listing-10",
    title: "Cozy Studio in Pulchowk",
    type: "apartment",
    location: "Pulchowk, Lalitpur",
    price: 13500,
    photo: ROOM_PHOTOS.roomLarge,
    isVerified: true,
    genderPreference: "any",
    amenities: ["WiFi", "Kitchen", "Furnished"],
    rating: 4.6,
    reviewCount: 19,
    availableFrom: "1 May",
    landlordTrustScore: 91,
    postedDaysAgo: 2,
    matchScore: 88,
    matchReasons: ["Budget Match", "WiFi Available"],
  },
  {
    id: "listing-11",
    title: "Hostel Room Near New Baneshwor",
    type: "hostel",
    location: "Baneshwor, Kathmandu",
    price: 5000,
    photo: ROOM_PHOTOS.building3,
    isVerified: false,
    genderPreference: "male",
    amenities: ["WiFi", "Security"],
    rating: 3.9,
    reviewCount: 5,
    availableFrom: "Now",
    postedDaysAgo: 14,
  },
  {
    id: "listing-12",
    title: "Furnished Room, Maharajgunj",
    type: "room",
    location: "Maharajgunj, Kathmandu",
    price: 9500,
    photo: ROOM_PHOTOS.roomBright,
    isVerified: true,
    genderPreference: "female",
    amenities: ["Furnished", "WiFi", "Laundry"],
    rating: 4.7,
    reviewCount: 13,
    availableFrom: "Now",
    landlordTrustScore: 85,
    postedDaysAgo: 3,
  },
];
