import type { CommunityPostRow } from "./types";

/**
 * Mock community post rows for /admin/community.
 * TODO: Replace with: await db.communityPost.findMany({ ...pagination, ...filters })
 */
export const MOCK_COMMUNITY_POSTS: CommunityPostRow[] = [
  {
    id: "cp1",
    authorName: "Prashant K.C.",
    authorLocation: "Koteshwor, KTM",
    category: "question",
    title: "How do I verify a listing before paying a deposit?",
    content:
      "I found a room in Koteshwor but the owner is asking for a deposit before a viewing. Is this normal practice, or should I be cautious? Any tips on verifying listings safely would help.",
    hashtags: ["#SafetyFirst", "#Deposit"],
    comments: 24,
    likes: 156,
    reportCount: 0,
    status: "live",
    postedAt: "Oct 12, 2023",
    postedTime: "10:15 AM",
    reportedComments: [],
  },
  {
    id: "cp2",
    authorName: "Sneha Shrestha",
    authorLocation: "Lalitpur",
    category: "safety_alert",
    title: "Unsafe Neighborhood Alert",
    content:
      "Hey everyone, just wanted to warn everyone about the dark alley near the Koteshwor Chowk. I experienced some suspicious behavior last night around 10 PM. Please be careful when walking alone in that area after dark.",
    hashtags: ["#SafetyFirst", "#Koteshwor"],
    comments: 102,
    likes: 450,
    reportCount: 3,
    status: "flagged",
    postedAt: "Oct 11, 2023",
    postedTime: "02:45 PM",
    reportedComments: [
      {
        id: "rc1",
        authorName: "Umesh Thapa",
        timeAgo: "2h ago",
        quote: "This is fake news, don't listen to her. Koteshwor is perfectly fine.",
        reportedFor: "Harassment",
      },
      {
        id: "rc2",
        authorName: "Anonymous",
        isAnonymous: true,
        timeAgo: "5h ago",
        quote: "Actually it happened to my friend too. Shut up Umesh.",
        reportedFor: "Inappropriate Language",
      },
    ],
  },
  {
    id: "cp3",
    authorName: "Rohan Basnet",
    authorLocation: "Pokhara",
    category: "tip",
    title: "Cheap and reliable furniture shops near Lakeside",
    content:
      "Sharing a list of budget-friendly furniture shops I used when moving into my new place near Lakeside. Great for students furnishing a room on a tight budget.",
    hashtags: ["#MovingTips", "#Pokhara"],
    comments: 8,
    likes: 32,
    reportCount: 0,
    status: "removed",
    postedAt: "Oct 10, 2023",
    postedTime: "09:00 AM",
    reportedComments: [],
  },
  {
    id: "cp4",
    authorName: "Anita Gurung",
    authorLocation: "Baneshwor, KTM",
    category: "discussion",
    title: "Best areas for young professionals near New Baneshwor?",
    content:
      "Relocating for work and want to be close to New Baneshwor without breaking the budget. Would love to hear from people who live in the area — what's it really like day to day?",
    hashtags: ["#Relocation", "#Baneshwor"],
    comments: 41,
    likes: 88,
    reportCount: 0,
    status: "live",
    postedAt: "Oct 9, 2023",
    postedTime: "04:20 PM",
    reportedComments: [],
  },
  {
    id: "cp5",
    authorName: "Bikash Shrestha",
    authorLocation: "Jhamsikhel, Lalitpur",
    category: "safety_alert",
    title: "Water tanker scam warning in Jhamsikhel",
    content:
      "A few tenants in my building were approached by someone claiming to sell discounted water tanker deliveries and asked for advance payment. Turned out to be a scam. Be careful with unsolicited door-to-door offers.",
    hashtags: ["#SafetyFirst", "#Scam"],
    comments: 19,
    likes: 64,
    reportCount: 1,
    status: "flagged",
    postedAt: "Oct 8, 2023",
    postedTime: "11:05 AM",
    reportedComments: [
      {
        id: "rc3",
        authorName: "Suman Gurung",
        timeAgo: "1d ago",
        quote: "Same thing happened near my place too, glad someone posted this.",
        reportedFor: "Spam",
      },
    ],
  },
];

import type { AdminCommentRow } from "./types";

/**
 * Mock reported comment rows for the /admin/community Comments tab.
 * TODO: Replace with: await db.comment.findMany({ where: { reportCount: { gt: 0 } }, ... })
 */
export const MOCK_REPORTED_COMMENTS: AdminCommentRow[] = [
  {
    id: "cm1",
    authorName: "Umesh Thapa",
    authorVerified: false,
    content: "This is fake news, don't listen to her. Koteshwor is perfectly fine.",
    reportReason: "harassment",
    reportCount: 2,
    reportedBy: "Sneha Shrestha",
    likes: 1,
    status: "pending",
    postedAt: "Oct 11, 2023",
    timeAgo: "2h ago",
    discussionId: "cp2",
    discussionTitle: "Unsafe Neighborhood Alert",
    discussionCategory: "safety_alert",
    thread: [
      {
        id: "cm1",
        authorName: "Umesh Thapa",
        authorVerified: false,
        content: "This is fake news, don't listen to her. Koteshwor is perfectly fine.",
        likes: 1,
        timeAgo: "2h ago",
        reportReason: "harassment",
        isReported: true,
      },
      {
        id: "cm2",
        authorName: "Anonymous",
        authorVerified: false,
        content: "Actually it happened to my friend too. Shut up Umesh.",
        likes: 3,
        timeAgo: "5h ago",
        reportReason: "inappropriate_language",
        isReported: true,
      },
    ],
  },
  {
    id: "cm2",
    authorName: "Anonymous",
    authorVerified: false,
    content: "Actually it happened to my friend too. Shut up Umesh.",
    reportReason: "inappropriate_language",
    reportCount: 1,
    reportedBy: "Umesh Thapa",
    likes: 3,
    status: "pending",
    postedAt: "Oct 11, 2023",
    timeAgo: "5h ago",
    discussionId: "cp2",
    discussionTitle: "Unsafe Neighborhood Alert",
    discussionCategory: "safety_alert",
    thread: [
      {
        id: "cm1",
        authorName: "Umesh Thapa",
        authorVerified: false,
        content: "This is fake news, don't listen to her. Koteshwor is perfectly fine.",
        likes: 1,
        timeAgo: "2h ago",
        reportReason: "harassment",
        isReported: true,
      },
      {
        id: "cm2",
        authorName: "Anonymous",
        authorVerified: false,
        content: "Actually it happened to my friend too. Shut up Umesh.",
        likes: 3,
        timeAgo: "5h ago",
        reportReason: "inappropriate_language",
        isReported: true,
      },
    ],
  },
  {
    id: "cm3",
    authorName: "Rajiv Koirala",
    authorVerified: false,
    content: "Everyone in that building is scamming people, avoid all listings from there.",
    reportReason: "misinformation",
    reportCount: 4,
    reportedBy: "Suman Gurung",
    likes: 0,
    status: "pending",
    postedAt: "Oct 8, 2023",
    timeAgo: "1d ago",
    discussionId: "cp5",
    discussionTitle: "Water tanker scam warning in Jhamsikhel",
    discussionCategory: "safety_alert",
    thread: [
      {
        id: "rc3",
        authorName: "Suman Gurung",
        authorVerified: true,
        content: "Same thing happened near my place too, glad someone posted this.",
        likes: 6,
        timeAgo: "1d ago",
      },
      {
        id: "cm3",
        authorName: "Rajiv Koirala",
        authorVerified: false,
        content: "Everyone in that building is scamming people, avoid all listings from there.",
        likes: 0,
        timeAgo: "1d ago",
        reportReason: "misinformation",
        isReported: true,
      },
    ],
  },
  {
    id: "cm4",
    authorName: "Deepak Malla",
    authorVerified: true,
    content: "Check out my page for cheap rooms, DM me on Instagram @deepak_rentals",
    reportReason: "spam",
    reportCount: 5,
    reportedBy: "Multiple users",
    likes: 0,
    status: "removed",
    postedAt: "Oct 5, 2023",
    timeAgo: "6d ago",
    discussionId: "cp4",
    discussionTitle: "Best areas for young professionals near New Baneshwor?",
    discussionCategory: "discussion",
    thread: [
      {
        id: "cm4",
        authorName: "Deepak Malla",
        authorVerified: true,
        content: "Check out my page for cheap rooms, DM me on Instagram @deepak_rentals",
        likes: 0,
        timeAgo: "6d ago",
        reportReason: "spam",
        isReported: true,
      },
    ],
  },
  {
    id: "cm5",
    authorName: "Kritika Adhikari",
    authorVerified: true,
    content: "I disagree, but let's keep this civil — everyone has different budgets to work with.",
    reportReason: "other",
    reportCount: 1,
    reportedBy: "Anonymous",
    likes: 9,
    status: "approved",
    postedAt: "Oct 3, 2023",
    timeAgo: "8d ago",
    discussionId: "cp1",
    discussionTitle: "How do I verify a listing before paying a deposit?",
    discussionCategory: "question",
    thread: [
      {
        id: "cm5",
        authorName: "Kritika Adhikari",
        authorVerified: true,
        content: "I disagree, but let's keep this civil — everyone has different budgets to work with.",
        likes: 9,
        timeAgo: "8d ago",
        reportReason: "other",
        isReported: true,
      },
    ],
  },
];
