import type { AnnouncementRow } from "./types";

/**
 * Mock announcement rows for /admin/announcements.
 * TODO: Replace with: await db.announcement.findMany({ ...pagination, ...filters })
 */
export const MOCK_ANNOUNCEMENTS: AnnouncementRow[] = [
  {
    id: "an1",
    title: "New Terms of Service",
    body: "We've updated our Terms of Service to improve clarity around deposits and cancellations. Please review the changes before your next booking.",
    scope: "system",
    audience: "all",
    priority: "info",
    status: "published",
    channels: ["in_app", "email"],
    isPinned: true,
    views: 4281,
    createdAgo: "Published 2 days ago",
  },
  {
    id: "an2",
    title: "Holiday Maintenance Alert",
    body: "Scheduled maintenance on Dec 24 between 1-3 AM NPT. Listing management tools will be temporarily unavailable for room owners.",
    scope: "system",
    audience: "owners",
    priority: "warning",
    status: "scheduled",
    channels: ["in_app"],
    isPinned: false,
    views: 0,
    createdAgo: "Scheduled for Dec 24",
    scheduledFor: "2024-12-24T01:00",
  },
  {
    id: "an3",
    title: "Welcome Offer: 20% Off Plus",
    body: "New room seekers get 20% off their first month of RoomMate Nepal Plus. Verify your profile to unlock the discount.",
    scope: "community",
    audience: "seekers",
    priority: "info",
    status: "published",
    channels: ["in_app", "push"],
    isPinned: false,
    views: 12402,
    createdAgo: "Published 1 week ago",
  },
  {
    id: "an4",
    title: "Community Guidelines Update",
    body: "We've clarified our safety-alert posting guidelines to reduce false reports. Read the updated community guidelines before posting.",
    scope: "community",
    audience: "all",
    priority: "info",
    status: "draft",
    channels: ["in_app"],
    isPinned: false,
    views: 0,
    createdAgo: "Draft saved 3 hours ago",
  },
  {
    id: "an5",
    title: "Critical: Payment Gateway Outage",
    body: "Our payment partner is experiencing an outage. Deposit payments may fail intermittently. Our team is actively monitoring the situation.",
    scope: "system",
    audience: "all",
    priority: "critical",
    status: "archived",
    channels: ["in_app", "email", "push"],
    isPinned: false,
    views: 8901,
    createdAgo: "Archived 3 weeks ago",
  },
];
